# DenseNet Training Configuration

DATA:
  # Dataset Configuration
  DATASET: 'medium_imagenet'  # Uses the existing MediumImagenetHDF5Dataset
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'  # Path to HDF5 file
  IMG_SIZE: 96  
  BATCH_SIZE: 64  # Significantly reduced batch size
  NUM_WORKERS: 6
  PIN_MEMORY: true

MODEL:
  NAME: 'densenet'  # For identification in main.py
  NUM_CLASSES: 200  # Set to 200 for medium_imagenet

TRAIN:
  EPOCHS: 100
  LR: 0.001
  OPTIMIZER:
    NAME: 'adamw'  # For compatibility with main.py

# Other Parameters
SEED: 42
OUTPUT: 'output/densenet'
SAVE_FREQ: 5
PRINT_FREQ: 100 