AUG:
  COLOR_JITTER: 0.4
  MIXUP: 0.2
  CUTMIX: 0.2
  LABEL_SMOOTHING: 0.1
DATA:
  BATCH_SIZE: 1024
  DATASET: "cifar10"
  IMG_SIZE: 32
MODEL:
  NAME: "resnetv2"
  VARIANT: "resnet18"  # Options: resnet18, resnet34, resnet50, resnet101, resnet152
  NUM_CLASSES: 10
  DROP_RATE: 0.0
  ZERO_INIT_RESIDUAL: True
  USE_SE: False
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  LR: 3e-4
  MIN_LR: 3e-5
  WARMUP_LR: 3e-5
  LR_SCHEDULER:
    NAME: "cosine"  # Options: cosine, step, warmup_cosine, one_cycle
    STEP_SIZE: 30  # For step scheduler
    GAMMA: 0.1  # For step scheduler
    MAX_LR: 1e-3  # For one_cycle scheduler
  OPTIMIZER:
    NAME: "sgd"  # Options: sgd, adam, adamw
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.01
OUTPUT: "output/resnetv2_cifar"
SAVE_FREQ: 50 
PRINT_FREQ: 500 