AUG:
  COLOR_JITTER: 0.4
DATA:
  BATCH_SIZE: 256  # Default value, overridden in command to 256
  DATASET: "medium_imagenet"
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'
  IMG_SIZE: 96
  NUM_WORKERS: 8  # Default value, overridden in command to 32
  PIN_MEMORY: True  # Enabled via --pin-memory in command
  PERSISTENT_WORKERS: True
  PREFETCH_FACTOR: 2  # Default value, overridden in command to 4
MODEL:
  NAME: "resnet"  # Original ResNet, not ResNetV2
  VARIANT: "resnet18"  
  NUM_CLASSES: 200
  DROP_RATE: 0.0
  ENABLE_CHECKPOINT: False  # Enabled via --enable-checkpoint in command
TRAIN:
  EPOCHS: 100  # Default value, overridden in command to 20
  WARMUP_EPOCHS: 5
  LR: 0.01  # Default value, overridden in command to 0.001
  MIN_LR: 0.0001
  LR_SCHEDULER:
    NAME: "cosine"  # Cosine annealing learning rate schedule
  OPTIMIZER:
    NAME: "sgd"  # Default value, overridden in command to adamw
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    NESTEROV: True
  USE_AMP: True  # Enabled via --use-amp in command
MEMORY:
  EMPTY_CACHE_FREQ: 50  # Empty CUDA cache every 50 batches
OUTPUT: "output/resnet18_medium_imagenet"
SAVE_FREQ: 5 
PRINT_FREQ: 100
VALIDATE_FREQ: 1  # Default value, overridden in command to 5 