BASE: ['resnetv2_base.yaml']
MODEL:
  VARIANT: "resnet50"  # Will be renamed to resnet50v2 in code
  USE_SE: True  # Enable Squeeze-and-Excitation blocks for improved accuracy
  DROP_RATE: 0.3  # Higher dropout for more regularization (matches ResNet18v2)
  STOCHASTIC_DEPTH_RATE: 0.2  # Added stochastic depth for improved regularization
  ZERO_INIT_RESIDUAL: True  # Zero-initialize the last BN in each residual branch
DATA:
  BATCH_SIZE: 128  # Standard batch size for ResNet50
TRAIN:
  EPOCHS: 60  # Standard epochs for medium-sized networks
  LR: 0.01  # Literature-standard LR for ResNet50
  OPTIMIZER:
    NAME: "sgd"
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001  # Standard weight decay from literature
    NESTEROV: True  # Enable Nesterov momentum for better convergence
  WARMUP_EPOCHS: 10  # Extended warmup period for more stable training
  GRADIENT_ACCUMULATION_STEPS: 2  # Increase effective batch size with gradient accumulation
  GRADIENT_CLIP_VAL: 1.0  # Added gradient clipping for stability
AUG:
  MIXUP: 0.4  # Increased mixup alpha based on literature
  CUTMIX: 0.4  # Increased cutmix alpha based on literature
  LABEL_SMOOTHING: 0.1  # Standard label smoothing value
  COLOR_JITTER: 0.5  # Increased color jittering
  RANDOM_ERASING: 0.25  # Added random erasing with 25% probability
OUTPUT: "output/resnet50v2_medium_imagenet_antioverfitting" 