AUG:
  COLOR_JITTER: 0.4
  MIXUP: 0.2
  CUTMIX: 0.2
  LABEL_SMOOTHING: 0.1
DATA:
  BATCH_SIZE: 128
  DATASET: "medium_imagenet"
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'
  IMG_SIZE: 96
  NUM_WORKERS: 8
  PIN_MEMORY: True
  PERSISTENT_WORKERS: True
  PREFETCH_FACTOR: 2
MODEL:
  NAME: "resnetv2"
  VARIANT: "resnet18"  # Options: resnet18, resnet34, resnet50, resnet101, resnet152
  NUM_CLASSES: 200
  DROP_RATE: 0.0
  ZERO_INIT_RESIDUAL: True
  USE_SE: False
TRAIN:
  EPOCHS: 60
  WARMUP_EPOCHS: 5
  LR: 0.01
  MIN_LR: 0.0001
  LR_SCHEDULER:
    NAME: "cosine"  # Literature recommendation: cosine with warmup
  OPTIMIZER:
    NAME: "sgd"  # Literature recommendation: SGD with momentum
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    NESTEROV: True
  USE_AMP: True  # Use mixed precision training
  GRADIENT_CLIP_VAL: 1.0
  GRADIENT_ACCUMULATION_STEPS: 1
MEMORY:
  EMPTY_CACHE_FREQ: 50  # Empty CUDA cache every 50 batches
OUTPUT: "output/"
SAVE_FREQ: 5 
PRINT_FREQ: 100
VALIDATE_FREQ: 1 