BASE: ['resnetv2_base.yaml']
MODEL:
  VARIANT: "resnet101"  # Will be renamed to resnet101v2 in code
  USE_SE: True  # Enable Squeeze-and-Excitation blocks for improved accuracy
  DROP_RATE: 0.3  # Higher dropout for deep network regularization
DATA:
  BATCH_SIZE: 64  # Smaller batch size for deeper network
TRAIN:
  EPOCHS: 60  # Standard epochs for large networks
  LR: 0.005  # Lower initial learning rate for deeper networks
  OPTIMIZER:
    NAME: "sgd"
    WEIGHT_DECAY: 0.0001  # Standard weight decay
  GRADIENT_ACCUMULATION_STEPS: 4  # More gradient accumulation to increase effective batch size
  GRADIENT_CLIP_VAL: 1.0  # Clip gradients for stability in deeper networks
MEMORY:
  EMPTY_CACHE_FREQ: 20  # Clear memory more frequently for larger model
OUTPUT: "output/resnet101v2_medium_imagenet" 