DATA:
  DATASET: "medium_imagenet"
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'
  IMG_SIZE: 224
  NUM_WORKERS: 8
  PIN_MEMORY: True
  PREFETCH_FACTOR: 2
  PERSISTENT_WORKERS: True

MODEL:
  NUM_CLASSES: 200
  DROP_RATE: 0.1
  SMALL_INPUTS: False
  RESNEXT:
    CARDINALITY: 32
    BASE_WIDTH: 4
    PRUNING_RATE: 1.0  # Default: No pruning, override in model-specific config
    ACTIVATION: "relu"  # Options: relu, relu6, silu
    USE_CHECKPOINT: False  # Default: No checkpoint, override for larger models

TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  GRADIENT_ACCUMULATION_STEPS: 1  # Default, changed for larger models
  USE_AMP: True  # Enable automatic mixed precision training
  OPT_LEVEL: "O1"  # Mixed precision optimization level
  OPTIMIZER:
    NAME: "sgd"
    MOMENTUM: 0.9
  LR_SCHEDULER:
    NAME: "cosine"

AUG:
  COLOR_JITTER: 0.4
  RAND_AUGMENT: "rand-m9-mstd0.5-inc1"

SAVE_FREQ: 5
SEED: 42 