BASE: ['resnext_base.yaml']

DATA:
  DATASET: "medium_imagenet"
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'
  IMG_SIZE: 224
  BATCH_SIZE: 64
  NUM_WORKERS: 8

MODEL:
  NAME: "resnext50"
  RESNEXT:
    CARDINALITY: 32
    BASE_WIDTH: 4
    PRUNING_RATE: 0.9
    ACTIVATION: "silu"
    USE_CHECKPOINT: False

TRAIN:
  EPOCHS: 100
  LR: 0.05
  OPTIMIZER:
    NAME: "sgd"
    MOMENTUM: 0.9
  LR_SCHEDULER:
    NAME: "cosine"
  GRADIENT_ACCUMULATION_STEPS: 2

OUTPUT: "output/resnext50_imagenet"
SAVE_FREQ: 5
SEED: 42 