BASE: ['resnetv2_base.yaml']
DATA:
  BATCH_SIZE: 32
  DATASET: "medium_imagenet"
  MEDIUM_IMAGENET_PATH: '/honey/nmep/medium-imagenet-96.hdf5'
  IMG_SIZE: 96
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NUM_CLASSES: 200
  VARIANT: "resnet50"  # Use ResNet50 for better performance on Medium ImageNet
  USE_SE: True  # Enable Squeeze-and-Excitation blocks
  DROP_RATE: 0.2  # Add some dropout for regularization
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 3
  LR: 0.0005
  MIN_LR: 5e-5
  LR_SCHEDULER:
    NAME: "warmup_cosine"  # Use warmup cosine schedule
OUTPUT: "output/resnetv2_medium_imagenet"
SAVE_FREQ: 1
PRINT_FREQ: 50 


